from qt_core import *

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(Qt.NonModal)
        Form.resize(392, 522)
        self.saveBtn = QPushButton(Form)
        self.saveBtn.setGeometry(QRect(210, 480, 81, 31))
        self.saveBtn.setObjectName("saveBtn")
        self.closeBtn = QPushButton(Form)
        self.closeBtn.setGeometry(QRect(300, 480, 81, 31))
        self.closeBtn.setObjectName("closeBtn")
        self.groupBox = QGroupBox(Form)
        self.groupBox.setGeometry(QRect(10, 20, 371, 51))
        self.groupBox.setObjectName("groupBox")
        self.input_sheetname = QLineEdit(self.groupBox)
        self.input_sheetname.setGeometry(QRect(10, 20, 351, 20))
        self.input_sheetname.setObjectName("input_sheetname")
        self.groupBox_2 = QGroupBox(Form)
        self.groupBox_2.setGeometry(QRect(10, 90, 371, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.input_sheeturl = QLineEdit(self.groupBox_2)
        self.input_sheeturl.setGeometry(QRect(10, 20, 351, 20))
        self.input_sheeturl.setObjectName("input_sheeturl")
        self.groupBox_3 = QGroupBox(Form)
        self.groupBox_3.setGeometry(QRect(10, 140, 371, 331))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QRect(10, 20, 161, 51))
        font = QFont()
        font.setBold(True)
        font.setLegacyWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.comboBox = QComboBox(self.groupBox_4)
        self.comboBox.setGeometry(QRect(10, 20, 141, 22))
        self.comboBox.setObjectName("comboBox")
        self.groupBox_5 = QGroupBox(self.groupBox_3)
        self.groupBox_5.setGeometry(QRect(190, 20, 161, 51))
        font = QFont()
        font.setBold(True)
        font.setLegacyWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.comboBox_2 = QComboBox(self.groupBox_5)
        self.comboBox_2.setGeometry(QRect(10, 20, 141, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.groupBox_6 = QGroupBox(self.groupBox_3)
        self.groupBox_6.setGeometry(QRect(10, 80, 161, 51))
        font = QFont()
        font.setBold(True)
        font.setLegacyWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.comboBox_3 = QComboBox(self.groupBox_6)
        self.comboBox_3.setGeometry(QRect(10, 20, 141, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.groupBox_7 = QGroupBox(self.groupBox_3)
        self.groupBox_7.setGeometry(QRect(190, 80, 161, 51))
        font = QFont()
        font.setBold(True)
        font.setLegacyWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.comboBox_4 = QComboBox(self.groupBox_7)
        self.comboBox_4.setGeometry(QRect(10, 20, 141, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.groupBox_8 = QGroupBox(self.groupBox_3)
        self.groupBox_8.setGeometry(QRect(10, 140, 161, 51))
        font = QFont()
        font.setBold(True)
        font.setLegacyWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.comboBox_5 = QComboBox(self.groupBox_8)
        self.comboBox_5.setGeometry(QRect(10, 20, 141, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.groupBox_9 = QGroupBox(self.groupBox_3)
        self.groupBox_9.setGeometry(QRect(190, 140, 161, 51))
        font = QFont()
        font.setBold(True)
        font.setLegacyWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.comboBox_7 = QComboBox(self.groupBox_9)
        self.comboBox_7.setGeometry(QRect(10, 20, 141, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.groupBox_10 = QGroupBox(self.groupBox_3)
        self.groupBox_10.setGeometry(QRect(10, 200, 161, 51))
        font = QFont()
        font.setBold(True)
        font.setLegacyWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.comboBox_8 = QComboBox(self.groupBox_10)
        self.comboBox_8.setGeometry(QRect(10, 20, 141, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.groupBox_11 = QGroupBox(self.groupBox_3)
        self.groupBox_11.setGeometry(QRect(190, 200, 161, 51))
        font = QFont()
        font.setBold(True)
        font.setLegacyWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.comboBox_9 = QComboBox(self.groupBox_11)
        self.comboBox_9.setGeometry(QRect(10, 20, 141, 22))
        self.comboBox_9.setObjectName("comboBox_9")
        self.groupBox_12 = QGroupBox(self.groupBox_3)
        self.groupBox_12.setGeometry(QRect(10, 260, 161, 51))
        font = QFont()
        font.setBold(True)
        font.setLegacyWeight(75)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.comboBox_10 = QComboBox(self.groupBox_12)
        self.comboBox_10.setGeometry(QRect(10, 20, 141, 22))
        self.comboBox_10.setObjectName("comboBox_10")
        self.groupBox_13 = QGroupBox(self.groupBox_3)
        self.groupBox_13.setGeometry(QRect(190, 260, 161, 51))
        font = QFont()
        font.setBold(True)
        font.setLegacyWeight(75)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName("groupBox_13")
        self.comboBox_11 = QComboBox(self.groupBox_13)
        self.comboBox_11.setGeometry(QRect(10, 20, 141, 22))
        self.comboBox_11.setObjectName("comboBox_11")
        self.testBtn = QPushButton(Form)
        self.testBtn.setGeometry(QRect(120, 480, 81, 31))
        self.testBtn.setObjectName("testBtn")

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.saveBtn.setText(_translate("Form", "저 장"))
        self.closeBtn.setText(_translate("Form", "닫 기"))
        self.groupBox.setTitle(_translate("Form", "시트 명"))
        self.groupBox_2.setTitle(_translate("Form", "시트 URL"))
        self.groupBox_3.setTitle(_translate("Form", "시트 설정"))
        self.groupBox_4.setTitle(_translate("Form", "No"))
        self.groupBox_5.setTitle(_translate("Form", "수취인명"))
        self.groupBox_6.setTitle(_translate("Form", "구매처"))
        self.groupBox_7.setTitle(_translate("Form", "구매가격"))
        self.groupBox_8.setTitle(_translate("Form", "택배사"))
        self.groupBox_9.setTitle(_translate("Form", "운송장번호"))
        self.groupBox_10.setTitle(_translate("Form", "주문번호"))
        self.groupBox_11.setTitle(_translate("Form", "우편번호"))
        self.groupBox_12.setTitle(_translate("Form", "구매시간"))
        self.groupBox_13.setTitle(_translate("Form", "주문고유번호"))
        self.testBtn.setText(_translate("Form", "테스트"))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    Form = QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
