
from qt_core import *


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(Qt.NonModal)
        Form.resize(393, 593)
        self.saveBtn = QPushButton(Form)
        self.saveBtn.setGeometry(QRect(140, 520, 111, 61))
        self.saveBtn.setObjectName("saveBtn")
        self.closeBtn = QPushButton(Form)
        self.closeBtn.setGeometry(QRect(270, 520, 111, 61))
        self.closeBtn.setObjectName("closeBtn")
        self.tryloginBtn = QPushButton(Form)
        self.tryloginBtn.setGeometry(QRect(10, 520, 111, 61))
        self.tryloginBtn.setObjectName("tryloginBtn")
        self.groupBox = QGroupBox(Form)
        self.groupBox.setGeometry(QRect(10, 20, 371, 80))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QRect(10, 20, 351, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.selectloginTypeList = QComboBox(self.gridLayoutWidget)
        self.selectloginTypeList.setObjectName("selectloginTypeList")
        self.gridLayout.addWidget(self.selectloginTypeList, 1, 1, 1, 1)
        self.selectmallNameList = QComboBox(self.gridLayoutWidget)
        self.selectmallNameList.setObjectName("selectmallNameList")
        self.gridLayout.addWidget(self.selectmallNameList, 1, 0, 1, 1)
        self.groupBox_2 = QGroupBox(Form)
        self.groupBox_2.setGeometry(QRect(10, 110, 371, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QRect(10, 20, 351, 101))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.loginIdLineEdit = QLineEdit(self.gridLayoutWidget_2)
        self.loginIdLineEdit.setObjectName("loginIdLineEdit")
        self.gridLayout_2.addWidget(self.loginIdLineEdit, 0, 0, 1, 1)
        self.loginPassLineEdit = QLineEdit(self.gridLayoutWidget_2)
        self.loginPassLineEdit.setEchoMode(QLineEdit.Password)
        self.loginPassLineEdit.setObjectName("loginPassLineEdit")
        self.gridLayout_2.addWidget(self.loginPassLineEdit, 1, 0, 1, 1)
        self.nickNameLineEdit = QLineEdit(self.gridLayoutWidget_2)
        self.nickNameLineEdit.setEchoMode(QLineEdit.Normal)
        self.nickNameLineEdit.setObjectName("nickNameLineEdit")
        self.gridLayout_2.addWidget(self.nickNameLineEdit, 2, 0, 1, 1)
        self.groupBox_3 = QGroupBox(Form)
        self.groupBox_3.setGeometry(QRect(10, 390, 371, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_4 = QWidget(self.groupBox_3)
        self.gridLayoutWidget_4.setGeometry(QRect(10, 20, 351, 73))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textEdit = QTextEdit(self.gridLayoutWidget_4)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_4.addWidget(self.textEdit, 0, 0, 1, 1)
        self.groupBox_4 = QGroupBox(Form)
        self.groupBox_4.setGeometry(QRect(10, 260, 371, 111))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayoutWidget_5 = QWidget(self.groupBox_4)
        self.gridLayoutWidget_5.setGeometry(QRect(10, 20, 351, 81))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.emailIdLineEdit = QLineEdit(self.gridLayoutWidget_5)
        self.emailIdLineEdit.setObjectName("emailIdLineEdit")
        self.gridLayout_5.addWidget(self.emailIdLineEdit, 0, 0, 1, 1)
        self.emailPassLineEdit_3 = QLineEdit(self.gridLayoutWidget_5)
        self.emailPassLineEdit_3.setEchoMode(QLineEdit.Password)
        self.emailPassLineEdit_3.setObjectName("emailPassLineEdit_3")
        self.gridLayout_5.addWidget(self.emailPassLineEdit_3, 1, 0, 1, 1)
        self.pushButton = QPushButton(self.gridLayoutWidget_5)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.saveBtn.setText(_translate("Form", "추 가(저 장)"))
        self.closeBtn.setText(_translate("Form", "닫 기"))
        self.tryloginBtn.setText(_translate("Form", "로그인 테스트"))
        self.groupBox.setTitle(_translate("Form", "쇼핑몰 선택"))
        self.groupBox_2.setTitle(_translate("Form", "로그인 정보"))
        self.loginIdLineEdit.setPlaceholderText(_translate("Form", "*쇼핑몰 아이디를 입력하세요 :"))
        self.loginPassLineEdit.setPlaceholderText(_translate("Form", "*쇼핑몰 비밀번호를 입력하세요 :"))
        self.nickNameLineEdit.setPlaceholderText(_translate("Form", "쇼핑몰을 구분할 닉네임을 입력하세요 :"))
        self.groupBox_3.setTitle(_translate("Form", "메모"))
        self.groupBox_4.setTitle(_translate("Form", "2차 인증 정보"))
        self.emailIdLineEdit.setPlaceholderText(_translate("Form", "*이메일 아이디를 입력하세요 :"))
        self.emailPassLineEdit_3.setPlaceholderText(_translate("Form", "*이메일 비밀번호를 입력하세요 :"))
        self.pushButton.setText(_translate("Form", "인 증"))


if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    Form = QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
